#!/bin/sh -f

app="`pwd`"
app="`dirname ${app}`"
app="`basename ${app}`"

APP="`echo ${app} | tr '[:lower:]' '[:upper:]'`"

if [ -f ../${app}/version ] ; then
  maj_vers="`grep ${APP}_MAJOR_VERSION ../${app}/version | awk '{print $3}'`"
  min_vers="`grep ${APP}_MINOR_VERSION ../${app}/version | awk '{print $3}'`"
fi

if [ -f ./version ] ; then
  maj_vers="`grep ${APP}_MAJOR_VERSION ./version | awk '{print $3}'`"
  min_vers="`grep ${APP}_MINOR_VERSION ./version | awk '{print $3}'`"
fi

version="${maj_vers}.${min_vers}"

echo ${version}
