#!/bin/sh -f

bush_home=`dirname $0`

app="`${bush_home}/app_name`"

APP="`echo ${app} | tr '[:lower:]' '[:upper:]'`"
maj_vers="`grep ${APP}_MAJOR_VERSION ../${app}/version | awk '{print $3}'`"
min_vers="`grep ${APP}_MINOR_VERSION ../${app}/version | awk '{print $3}'`"
pat_vers="`grep ${APP}_PATCH_VERSION ../${app}/version | awk '{print $3}'`"

branch="${app}_${maj_vers}_${min_vers}_${pat_vers}"

if [ $# = 0 ] ; then
  echo "bush/branch_release : branch will be : ${branch}"
  exit
fi

save_dir=`pwd`

tos="${save_dir}"
tos="${tos} ${save_dir}/../../inexlib/inlib"
tos="${tos} ${save_dir}/../../inexlib/exlib"
tos="${tos} ${save_dir}/../../inexlib/ourex"
tos="${tos} ${save_dir}/../../inexlib"

if [ -d "${HOME}/Documents/${app}/.git" ] ; then
  tos="${tos} /Users/barrand/Documents/${app}"
fi

for dir in ${tos} ; do
  if [ -d ${dir} ] ; then
    echo "bush/branch_release : ${dir} : create branch ${branch}"
    cd ${dir}
#    git branch -D ${branch}
    git branch ${branch}
    cd ${save_dir}
  fi
done

cd ${save_dir}
