#!/bin/sh -f

if [ $# != 1 ] ; then
  echo 'bush/lines : give a directory path.'
  exit
fi

bush_home=`dirname $0`

find $1 -name '*' -type f -print > tmp_0

cc -o c_count ${bush_home}/c/c_count.c

# exclude some files :
grep -v 'lexer.l' ./tmp_0 > tmp_1;/bin/mv ./tmp_1 tmp_0

/bin/rm -f tmp_2
for file in $(cat tmp_0) ; do
  #echo ${file}
  ./c_count ${file} | grep ${file} >> tmp_2
done

awk 'BEGIN{x=0;}{x+=$0;}END{print x}' tmp_2

/bin/rm -f ./tmp_0 ./tmp_2 c_count
